// fonts.h - GENERATED by tools/fontgen.py. DO NOT EDIT.
// Includes every anti-aliased gfx font. Regenerate: python tools/fontgen.py
//
// Glyphs rasterized from Barlow Semi Condensed, Copyright 2017 The Barlow
// Project Authors (https://github.com/jpt/barlow), licensed under the SIL
// Open Font License, Version 1.1 (see tools/fonts/OFL.txt,
// https://openfontlicense.org). This generated bitmap font is a derivative
// work distributed under the same license.
//
// name        weight    em  asc desc line  cap digitH digitAdv  flash
// F_LABEL     SemiBold   13   13    3   16    9      9        7   4868
// F_SMALL     Medium     15   15    3   18   10     10        8   5751
// F_BODY      Medium     18   18    4   22   12     13        9   7218
// F_BODYB     SemiBold   18   18    4   22   13     13        9   7543
// F_TITLE     SemiBold   24   24    5   29   17     17       13  11406
// F_NUM_M     Bold       32   32    7   39   22     23       17  19274
// F_NUM_L     Bold       56   56   12   68   39     40       30   6496
// F_NUM_XL    Bold      128  128   26  154   90     91       70  31766
// F_NUM_XXL   Bold      168  168   34  202  118    120       91  42562
// total font flash: 136884 bytes
#pragma once
#include "font_label.h"
#include "font_small.h"
#include "font_body.h"
#include "font_bodyb.h"
#include "font_title.h"
#include "font_num_m.h"
#include "font_num_l.h"
#include "font_num_xl.h"
#include "font_num_xxl.h"
